### ISSUE TITLE
Desenvolver a conexão de banco de dados do projeto

### ISSUE THREAD

**Issue by aocastro** [anavitoriambb/TCC#10]
Gerar a integração do banco de dados com o projeto, por meio de conexão PHP.

**Comment by anavitoriambb** [comment]
![image](https://user-images.githubusercontent.com/61321376/117724285-eab92380-b1b9-11eb-84cc-d54473ddb654.png)
![image](https://user-images.githubusercontent.com/61321376/117724329-fb699980-b1b9-11eb-96c5-d7d6de9ddfb7.png)
