### ISSUE TITLE
Proposta de layout para o site

### ISSUE THREAD

**Issue by aocastro** [anavitoriambb/TCC#11]
Desenvolver a nova proposta de site para a ONG.

- Página Inicial;
- Animais disponíveis para adoção;
- Portal transparência (local onde você apresentariam toda movimentação finaceira da instuição/doações)
- Volutanriar-se
- Entre outras....

**Comment by giovanamds** [comment]
![image](https://user-images.githubusercontent.com/61321458/117861702-1d215a00-b268-11eb-8145-d52b2285b539.png)
