### ISSUE TITLE
Normalização do banco de dados

### ISSUE THREAD

**Issue by aocastro** [anavitoriambb/TCC#4]
Uma vez que já foi definido o como funcionará o banco de dados, observa-se a necessidade de normalizar os nomes e atributos do banco de dados, como por exemplo:

Nome de tabela:

- voluntario
- VOLUNTARIO

Nome de atributos:

- nome
- NOME
- nomeCompleto
- nome_completo
- NOMECOMPLETO

**Comment by anavitoriambb** [comment]
![Normalização do Banco de Dados](https://user-images.githubusercontent.com/61321376/113636352-c0b79300-9648-11eb-95a3-158852dae6ef.jpeg)

**Comment by anavitoriambb** [comment]
![image](https://user-images.githubusercontent.com/61321376/143973016-4a920629-28aa-4533-ad04-8aae1c5f00ad.png)
