### ISSUE TITLE
Identidade visual da ONG

### ISSUE THREAD

**Issue by aocastro** [anavitoriambb/TCC#6]
Precisamos da logo, cores e tudo mais.

**Comment by biarachval** [comment]
Logo ONG refugio Pet Lins 

![ONG](https://user-images.githubusercontent.com/61592157/114417395-f21fe980-9b87-11eb-82b6-b504ff246ca4.jpeg)

Cor dos animais:
Cachorro(preto) HEX : #0a0b0d 
RGB : 10, 11, 13 
HSL  : 220, 13%, 4% 
Gato(laranja): HEX : #e67817
RGB : 230, 120, 23
HSL  : 28, 81%, 49%

Cor das letras:
(preto)HEX : #0a0b0d
RGB : 10, 11, 13
HSL  : 220, 13%, 4%

(bordô)HEX : #200005
RGB : 32, 0, 5
HSL  : 350, 100%, 6%

Cor sombreado:
(cinza)HEX : #827e7f
RGB : 130, 126, 127
HSL  : 345, 1%, 50%

(laranja claro) HEX : #de7c2c
RGB : 222, 124, 44
HSL  : 26, 72%, 52%
