### ISSUE TITLE
Domínio e hospedagem gratuita

### ISSUE THREAD

**Issue by aocastro** [anavitoriambb/TCC#7]
Gerar um domínio e hospedagem gratuita.

**Domínio, acesso FTP, acesso ao banco de dados.**

**Comment by anavitoriambb** [comment]
**Domínio:** 
http://refugiopet.infinityfreeapp.com/

**Dados de Acesso FTP:**

Nome do Host: ftpupload.net
Usuário FTP: epiz_28941053
Senha FTP: j8TNmmUdpBgG 
Porta FTP: 21



**Dados para Acesso ao Banco de Dados:**

Nome do Host: sql107.epizy.com
Porta do Banco de Dados: 3306 
Nome do Banco de Dados: epiz_28941053_refugiopet
Usuário do Banco de Dados: epiz_28941053
Senha do Banco de Dados: j8TNmmUdpBgG
